### PR TITLE
46 cleanup nav bar

### LINKED ISSUE #46: Cleanup nav bar
Need to cleanup the navbar with the following changes:
- remove external link
- remove resources dropdown
- Uppercase G in **guides**
- Update github icon link to point to our project
- Comment out code for dark mode for now, we can bring this back later if/when needed
- Update the navbar text color because when we're on the guides page, against the white background its hard to read the text. Maybe on the main page it stays the same color, and when we're on the guides page the text is black? @rcmtcristian @HondaChan14 any thoughts on this?

Image

### PR DESCRIPTION
**Pull request by rcmtcristian**
# Preview: 
Screenshot 2023-04-02 133702

 ### Description 
:recycle: Refactor: Trimmed navbar for better user experience. ```src/components/Header.astro```
:recycle: Refactor: Temporarily disabled dark mode due to unfinished style board. ```src/components/Header.astro```
:recycle: Refactor: Improved clarity and readability in Navigation component. ```src/components/Header.astro```
:bento: Update: Fixed incorrect URL in Guides component.
:memo: Update: Updated syntax for improved maintainability in Guides component.
:lipstick: Update: Enhanced styling in Header component for better visual appeal. ```src/pages/guides/[...page].astro```

### CODE REVIEW

**Comment by rcmtcristian** [comment]
Screenshot 2023-04-05 145104
I'm having a problem with the Get request not reading the file type properly. Maybe it has to do with the schema of the default layout but i have to check further. The type should be webp.

**Comment by adropofilm** [comment]
Looks good other than the gradient image missing, did you get a chance to figure that out @rcmtcristian?

**Comment by jamilsinno** [comment]
Gradient missing is a path adjustment in background class in the file [...page].astro

**Comment by ghost** [comment]
Closed - Refactored in issue #46 Due to conflicts with main branch

**Pull request closed without merging**
